Import('env')

InterpreterCommonLib = env.Library('InterpreterCommonLib', 'common.c')
env.Library('InterpreterLib', 'interpreter.c', LIBS=['InstructionLib'])#, CPPPATH=['.'])

env.Program('Interpreter', 'InterpreterMain.c', LIBS=['InterpreterLib', 'InstructionLib', 'InterpreterCommonLib'])
env.Program('Disassembler', 'disassembler.c', LIBS=['InstructionLib', 'InterpreterCommonLib'])