def options(opt):
	opt.load('compiler_c')
	opt.add_option('--mode', action='store', default='debug', help='Compile Mode: release or debug')


def configure(conf):
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')

	
	if conf.options.mode == 'debug':
		print "Setting up debug build"
		conf.env['CFLAGS'] = ['-g3', '-std=c89']
		conf.define("__LEX_DEBUG__", 1)
	else:
		print "Setting up release build"
		conf.env['CFLAGS'] = ['-ansi', '-std=c89']


def build(bld):
	from waflib.Build import POST_LAZY
	bld.post_mode = POST_LAZY

	bld.stlib(features='c', source='interpreter.c', target='InterpreterLib', includes='. ../Common', use='InstructionLib')
	bld.program(features='c', source='InterpreterMain.c', target="interpreter", includes=". ../Common", use="InterpreterLib", lib="m")
	bld.program(features='c', source='disassembler.c', target="disassembler", includes=". ../Common", use="InstructionLib")
def test(ctx):
	pass