import platform
recurseDirs = []

def options(opt):
	opt.load('compiler_c')

	opt.add_option('--mode', action='store', default='debug', help='Compile Mode: release or debug')
	opt.recurse(recurseDirs)

def configure(conf):
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')
	
	if conf.options.mode == 'debug':
		print "Setting up debug build"
		conf.env['CFLAGS'] = ['-g3', '-std=c89']
		conf.define("__LEX_DEBUG__", 1)
	else:
		print "Setting up release build"
		conf.env['CFLAGS'] = ['-ansi', '-std=c89']
	conf.recurse(recurseDirs)



def build(bld):
	bld.recurse(recurseDirs)

	from waflib.Build import POST_LAZY
	bld.post_mode = POST_LAZY

	assemblerLibBuild = bld.stlib(features='c', source='assembler.c', target='AssemblerLib', includes='. ../Common/ ../../Common')

def test(ctx):
	pass