Import('env')
SubScripts = ['Assembler/SConscript', 'Common/SConscript', 'Lexer_Parser/SConscript']

#prepare lemon
[Lemon, Lempar] = SConscript('Tools/SConscript', exports='env')


env.Append(CPPPATH=['#build/Compiler/Common'])
env.Append(LIBPATH=['#build/Compiler/Lexer_Parser', '#build/Compiler/Common', '#build/Compiler/Assembler'])

#build dependecies
SConscript(SubScripts, exports='env Lemon Lempar')

env.Library('CompilerLib', 'compiler.cpp')

env.Program('parserTest', 'parseTest.cpp', LIBS=['CompilerLib', 'LangLib', 'ProgramLib', 'FileUtil'])
env.Program('Compiler', 'CompilerMain.cpp', LIBS=['CompilerLib', 'LangLib', 'ProgramLib', 'AssemblerLib', 'InstructionLib', 'BytestreamLib'])