#define T_SEMICOLON                       1
#define T_IF                              2
#define T_LPAREN                          3
#define T_RPAREN                          4
#define T_LCURLY                          5
#define T_RCURLY                          6
#define T_DATATYPE                        7
#define T_KEYWORD                         8
#define T_EQUAL                           9
#define T_PLUS                           10
#define T_MINUS                          11
#define T_MUL                            12
#define T_DIV                            13
#define T_MOD                            14
#define T_EXP                            15
#define T_SYMBOL                         16
#define T_INTEGER                        17
#define T_FLOAT                          18
