import platform

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('flex')
	if not conf.env.FLEX:
		conf.fatal('Please install flex')
	
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')


def build(bld):

	bld.define("___LEX_LIBRARY___", 1)
	bld.add_group()
	#build lemon
	lemonBuild = bld(
		features='c cprogram',
		source='Tools/lemon.c',
		target='lemon')


	lemparCopy = bld(
		rule='cp ${SRC} ${TGT}',
		source='Tools/lempar.c',
		target='lempar.c'
		)
	
	lemonExecutable = bld.out_dir + "/Compiler/lemon"
	if platform.system() == "Windows":
		lemonExecutable += ".exe"
	bld.add_group()
	lemonit = bld(rule= lemonExecutable + " ${SRC}", source='Lang.y')

	flexit = bld(rule='${FLEX} -o${TGT} ${SRC}', source='Lang.lex', target='Lang.yy.c')
	bld.add_group()
	lexerBuild = bld(features='c cshlib', source='Lang.yy.c', target='Lang')


	compilerLibBuild = bld(features='c cshlib', source='compiler.c', target='CompilerLib', use='Lang')
	
	bld.add_group()
	compilerBuild = bld(
		features='c',
		source='compilerTest.c',
		use=['Lang', 'CompilerLib'],
		target='testCompiler')


def test(ctx):
	pass