
def options(opt):
	opt.load('compiler_c')

def configure(conf):
	print "here"
	conf.load('flex')
	if not conf.env.FLEX:
		conf.fatal('Please install flex')
	
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')

def build(bld):
	bld(rule='touch ${TGT}', target='Lang.yy.c')
	bld(rule='flex ${SRC} --outfile=${TGT}', source='Lang.lex', target='Lang.yy.c')