recurseDirs = []

def options(opt):
	opt.load('compiler_c')
	opt.add_option('--mode', action='store', default='debug', help='Compile Mode: release or debug')
	opt.recurse(recurseDirs)

def configure(conf):
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')

	if conf.options.mode == 'debug':
		print "Setting up debug build"
		conf.env['CFLAGS'] = ['-g3', '-std=c89']
	else:
		conf.env['CFLAGS'] = ['-std=c89']
	conf.recurse(recurseDirs)


def build(bld):
	bld.recurse(recurseDirs)
	bld.stlib(features='c', source='Instruction.c', target='InstructionLib')
	bld.stlib(features='c', source='FileUtil.c', target='FileUtil')
	bld.program(features='c', source="astackTest.c", target="astackTest", includes='.')

def test(ctx):
	pass