
def options(opt):
	opt.load('compiler_c')
	
def configure(conf):
	from waflib.Tools.compiler_c import c_compiler
	conf.load('compiler_c')
	if not conf.env.CC:
		conf.fatal('Please install a C compiler')



def build(bld):
	bld.stlib(features='c', source='program.c', target='ProgramLib', includes='. ..')

def test(ctx):
	pass