
Import('env')

#SConscript('CByteStream/SConscript', exports='env')

#env.Append(LIBPATH=['#build/Common/CByteStream'])

Library('BytestreamLib', 'Bytestream.cpp')

env.Library('InstructionLib', 'Instruction.cpp')
env.Library('FileUtil', 'FileUtil.cpp')

