#define T_SEMICOLON                        1
#define T_KEYWORD_IF                       2
#define T_LPAREN                           3
#define T_RPAREN                           4
#define T_LCURLY                           5
#define T_RCURLY                           6
#define T_KEYWORD_ELSE                     7
#define T_KEYWORD_WHILE                    8
#define T_EQUAL                            9
#define T_IDENTIFIER                      10
#define T_KEYWORD_PRINT                   11
#define T_KEYWORD_INTEGER                 12
#define T_KEYWORD_FLOAT                   13
#define T_LOGICAL_EQ                      14
#define T_LOGICAL_NE                      15
#define T_LOGICAL_GT                      16
#define T_LOGICAL_LT                      17
#define T_LOGICAL_GTE                     18
#define T_LOGICAL_LTE                     19
#define T_LOGICAL_AND                     20
#define T_LOGICAL_OR                      21
#define T_LOGICAL_XOR                     22
#define T_PLUS                            23
#define T_MINUS                           24
#define T_MUL                             25
#define T_DIV                             26
#define T_MOD                             27
#define T_EXP                             28
#define T_LOGICAL_NOT                     29
#define T_INTEGER                         30
#define T_FLOAT                           31
