Import('env Lemon Lempar')

#flex lexer
FlexBuilder = Builder(action = 'flex -o $TARGET $SOURCE')
env['BUILDERS']['Flex'] = FlexBuilder
env.Flex('LangLexer.c', 'LangLexer.l')

#setup lemon in local directory
LemonMove = env.Command('lemon', Lemon, Copy('$TARGET', '$SOURCE'))
LemparMove = env.Command('lempar.c', Lempar, Copy('$TARGET', '$SOURCE'))
Depends(LemonMove, Lemon)

#lemon parser
Lemony = env.Command('LangParse.c', '', action='pwd && ./lemon LangParse.y', chdir=1)
Depends(Lemony, LemparMove)
Depends(Lemony, LemonMove)

#compile LangLib
env.Append(CPPDEFINES=['___LEX_LIBRARY___'])
LangLib = env.Library('LangLib', ['LangLexer.c', Lemony, 'token.c'])#'LangParse.c', 'token.c'])
