#define T_SEMICOLON                        1
#define T_KEYWORD_IF                       2
#define T_LPAREN                           3
#define T_RPAREN                           4
#define T_LCURLY                           5
#define T_RCURLY                           6
#define T_KEYWORD_ELSE                     7
#define T_EQUAL                            8
#define T_IDENTIFIER                       9
#define T_KEYWORD_PRINT                   10
#define T_KEYWORD_INTEGER                 11
#define T_KEYWORD_FLOAT                   12
#define T_LOGICAL_EQ                      13
#define T_LOGICAL_NE                      14
#define T_LOGICAL_GT                      15
#define T_LOGICAL_LT                      16
#define T_LOGICAL_GTE                     17
#define T_LOGICAL_LTE                     18
#define T_PLUS                            19
#define T_MINUS                           20
#define T_MUL                             21
#define T_DIV                             22
#define T_MOD                             23
#define T_EXP                             24
#define T_INTEGER                         25
#define T_FLOAT                           26
