#define T_SEMICOLON                        1
#define T_IF                               2
#define T_LPAREN                           3
#define T_RPAREN                           4
#define T_LCURLY                           5
#define T_RCURLY                           6
#define T_EQUAL                            7
#define T_IDENTIFIER                       8
#define T_KEYWORD_INTEGER                  9
#define T_KEYWORD_FLOAT                   10
#define T_PLUS                            11
#define T_MINUS                           12
#define T_MUL                             13
#define T_DIV                             14
#define T_MOD                             15
#define T_EXP                             16
#define T_SYMBOL                          17
#define T_INTEGER                         18
#define T_FLOAT                           19
